"""WeatherGPT Prometheus Metrics Service.

Provides instrumentation counters, histograms, and gauges for system observability,
connector health, LLM latencies, ingestion performance, and risk alerts.
"""

from __future__ import annotations

import logging
from typing import Any

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
)

logger = logging.getLogger(__name__)

# Observation Metrics
OBSERVATIONS_TOTAL = Counter(
    "weathergpt_observations_total",
    "Total number of weather observations processed",
    ["source", "status"],
)

# Ingestion Pipeline Metrics
INGESTION_BATCH_TOTAL = Counter(
    "weathergpt_ingestion_batch_total",
    "Total batch ingestion runs executed",
    ["source", "status"],
)

PIPELINE_DURATION_SECONDS = Histogram(
    "weathergpt_pipeline_duration_seconds",
    "Time taken to execute ingestion pipeline runs",
    ["source"],
    buckets=[0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0],
)

# Connector Metrics
CONNECTOR_FETCH_TOTAL = Counter(
    "weathergpt_connector_fetch_total",
    "Total fetch attempts by external data connector",
    ["source", "status"],
)

CONNECTOR_LATENCY_SECONDS = Histogram(
    "weathergpt_connector_latency_seconds",
    "Latency of external connector data fetches",
    ["source"],
    buckets=[0.2, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0],
)

# Risk Alert Metrics
ALERTS_TOTAL = Counter(
    "weathergpt_alerts_total",
    "Total hazard risk alerts generated by the system",
    ["hazard_type", "severity"],
)

# LLM Inference Metrics
LLM_REQUESTS_TOTAL = Counter(
    "weathergpt_llm_requests_total",
    "Total LLM inference requests made by WeatherGPT RAG",
    ["provider", "status"],
)

LLM_LATENCY_SECONDS = Histogram(
    "weathergpt_llm_latency_seconds",
    "Latency in seconds for LLM query completions",
    ["provider"],
    buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 20.0, 45.0],
)

# Active Sessions
ACTIVE_CHAT_SESSIONS = Gauge(
    "weathergpt_chat_sessions_active",
    "Number of active WebSocket chat clients connected",
)


def get_prometheus_metrics() -> tuple[bytes, str]:
    """Generate Prometheus metric scrape payload and content type."""
    return generate_latest(), CONTENT_TYPE_LATEST
